name: in4k
encoding: utf-8
timezone: Europe/Lisbon
url: "http://in4k.github.io/"
highlighter: rouge
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
title: in4k
description: Website to archive knowledge, tools and resources on how to create demoscene productions below 1kb, 4kb or 8kbs.
