name: in4k
encoding: utf-8
timezone: Europe/Lisbon
url: "http://in4k.github.io/"
highlighter: rouge
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
future: true
